version: '3.8'

services:
  selenium:
    image: selenium/standalone-firefox:4.21.0-20240517
    container_name: linkedin-selenium
    ports:
      - "4444:4444"
      - "7900:7900" # VNC para debug visual
    volumes:
      - /dev/shm:/dev/shm:rw
      - /var/log/linkedin:/logs:rw
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=300
    restart: unless-stopped
    networks:
      - linkedin-net

  linkedin-poster:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    container_name: linkedin-poster
    depends_on:
      - selenium
    volumes:
      - /var/log/linkedin:/logs:rw
      - ./posts:/app/posts:rw
      - linkedin-cache:/app/.cache
    environment:
      # LinkedIn
      - LINKEDIN_EMAIL=${LINKEDIN_EMAIL}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}

      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # Telegram Bot
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_AUTHORIZED_USERS=${TELEGRAM_AUTHORIZED_USERS}

      # Alertas Telegram
      - TELEGRAM_ALERT_BOT_TOKEN=${TELEGRAM_ALERT_BOT_TOKEN}
      - TELEGRAM_ALERT_CHAT_ID=${TELEGRAM_ALERT_CHAT_ID}

      # Alertas Discord
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}

      # Docker mode
      - DOCKER_MODE=true
      - SELENIUM_HUB_URL=http://selenium:4444/wd/hub
    restart: unless-stopped
    networks:
      - linkedin-net
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

volumes:
  linkedin-cache:
    driver: local

networks:
  linkedin-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
