version: '3.8'

services:
  linkedin-poster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkedin-poster
    # Usar host networking para contornar problema de bridge
    network_mode: host
    volumes:
      - ./posts:/app/posts:rw
      - ./logs:/app/logs:rw
    environment:
      # LinkedIn
      - LINKEDIN_EMAIL=${LINKEDIN_EMAIL}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}

      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # Telegram Bot
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_AUTHORIZED_USERS=${TELEGRAM_AUTHORIZED_USERS}

      # Configurações técnicas
      - BROWSER=${BROWSER:-chrome}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - DOCKER_MODE=true
      - DISPLAY=:99
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    shm_size: 2gb
    # Não usar volumes nomeados para simplicidade

volumes:
  linkedin-cache:
    driver: local
