version: '3.8'

services:
  publicador:
    image: publicador
    network_mode: "host"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
    command: python3 docker_run.py
